### ISSUE TITLE
how to add a side menu to this

### ISSUE THREAD

**Issue by acylum** [Podmedics/ionic_starter#1]
I like your modular approach!  What I'm having trouble with is figuring out is how would I implement a sidemenu that would be available to all views like in the ionic sidemenu starter project?

**Comment by edwallitt** [comment]
This can be a little tricky but is certainly possible. The difficult part is having the sidemenu and navigation side by side.

The way we have done this in the past is by hooking up a app.main module and main.js file that includes the $ionicSideMenuDelegate (which you can use to access the sidemenu methods). We then have this Main controller as the root ng-controller of the app in our index.html

An excellent place to look for how this (and other Ionic stuff in fact) works is the [Ionic CodePen](http://codepen.io/ionic/pen/QwamEW). The code there is not structured in the same way we do things but it certainly shows what is possible really well and is not too difficult to reverse engineer.

**Comment by acylum** [comment]
Hmm - so are making a main view as the parent (abstract: true) for the sidemenu.  How would you get the other view i.e. feature2 or any other view to be linked to this sidemenu  - so it receives the side menu button at the top left?

Thanks

**Comment by edwallitt** [comment]
The Main controller you create will be the parent of all other controllers. We pop the ng-controller="Main' into the body tag in index.html

for example

```
<body ng-app="app" ng-controller="Main" >
    <ion-nav-view ></ion-nav-view>
</body>
```

All routes are then nested inside the main namespace through the router.

Here is an example on our main.html from on our apps

```
<ion-side-menus enable-menu-with-back-views="false">

    <ion-side-menu-content>

        <ion-nav-bar class="bar-positive">
            <ion-nav-buttons side="left">
                <button class="button button-icon button-clearhamburger_icon" menu-toggle="left">
                </button>
            </ion-nav-buttons>
        </ion-nav-bar>

        <ion-nav-view name="menuContent"></ion-nav-view>
    </ion-side-menu-content>

    <ion-side-menu side="left">

        <ion-header-bar class="bar-assertive">
            <div class="default_hospital_title">{{vm.defaultHospital.name}}</div>
        </ion-header-bar>

        <ion-content scroll="false">
            <ul class="list slide_out_navigation">
                <li><a ui-sref="main.tab.directory" class="item nav_directory" menu-close>Directory</a></li>
                <li><a ui-sref="main.dialer" class="item nav_quick_dial" menu-close>Quick Dial</a></li>
                <li><a ui-sref="main.codes" class="item nav_codes" menu-close>Codes</a></li>
                <li><a ui-sref="main.faqs" class="item nav_faqs" menu-close>FAQs</a></li>
                <li><a ui-sref="main.guidelines" class="item nav_guidelines" menu-close>Guidelines</a></li>
                <li><a ui-sref="main.map" class="item nav_local_map" menu-close>Local Map</a></li>
            </ul>
            <div class="navigation_fixed_bottom_links">
                <a ui-sref="main.settings" class="item nav_settings" menu-close>Settings</a>
            </div>
        </ion-content>
    </ion-side-menu>
</ion-side-menus>
```

Hope this helps.

**Comment by acylum** [comment]
So, i tried to modify the starter project to include a sidemenu.  I can't seem to get the side menu to show up/work.

What I did:: I made a main module (config.route.js,main.html, main.js, main.module.js) , added main scripts to index.html, and added app.main to app.module.js

Attached is a zip of the www folder - I hope you can help me figure out why side menu doesn't work.

Thanks

[Uploading www.zip…]()

**Comment by acylum** [comment]
So, i tried to modify the starter project to include a sidemenu. I can't seem to get the side menu to show up/work.

What I did:: I made a main module (config.route.js,main.html, main.js, main.module.js) , added main scripts to index.html, and added app.main to app.module.js

Attached is a zip of the www folder - I hope you can help me figure out why side menu doesn't work.

Thanks
[www.zip](https://github.com/Podmedics/ionic_starter/files/58340/www.zip)
