### ISSUE TITLE
Adding a new feature - get error

### ISSUE THREAD

**Issue by acylum** [Podmedics/ionic_starter#2]
I'm trying to learn how to work inside of this modular structure by adding a feature.  

I simply copied feature 2 as a new feature and renamed it feature 3. I renamed all files and content to reflect feature3 (config.route.js, feature3.html, feature3.js, feature3.module.js), then modified app.module.js  to add 'app.feature3' to the end of the list.   On running the app, I receive this error::

Error: [$injector:modulerr] Failed to instantiate module app due to:
[$injector:modulerr] Failed to instantiate module app.feature3 due to:
[$injector:nomod] Module 'app.feature3' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by edwallitt** [comment]
Hi - did you include the necessary js files in the index.html?(https://github.com/Podmedics/ionic_starter/blob/master/www/index.html)

Common issue that has bitten me in the past :)

**Comment by acylum** [comment]
Yup - that did it - thanks

**Comment by edwallitt** [comment]
Great!
